### ISSUE TITLE
PreProcTool does not run with the provided example files

### ISSUE THREAD

**Issue by brmiranda** [LANDIS-II-Foundation/LANDVIZ#34]
I downloaded and installed the new version of the PreProcTool, uninstalled the old version, and installed the new version. I also downloaded the example files from the website.  When I attempted to run the PreProcTool with the example files, I got the error below.  I am running on a Windows 7 computer.  The error message makes me believe that it is looking for something in the xml file that is not there.

=============
C:\Program Files (x86)\LANDIS-II\LandisPreProcTool
preproctool.exe
Start LANDIS-II PreProcTool
Setup application configuration
Create Project
preproc_VizTool_example.xml
Element 'landisPreProcProject': Missing child element(s). Expected is ( weblinks )., line 1, preproc_VizTool_example.xml
Press any key to continue . . .
=============

**Comment by mshukuno** [comment]
Hi Brian,


You are correct.  The application is looking for <weblinks></weblinks> tags in xml.  Please see "Testing" in Read me (https://github.com/LANDIS-II-Foundation/LANDVIZ).   The tag <weblinks></weblinks> need to be there in order to run the application without error.


I hope this helps.


Makiko

[https://avatars2.githubusercontent.com/u/12203695?s=400&v=4]<https://github.com/LANDIS-II-Foundation/LANDVIZ>

GitHub - LANDIS-II-Foundation/LANDVIZ: LANDVIZ Tool for ...<https://github.com/LANDIS-II-Foundation/LANDVIZ>
github.com
README.md LANDVIZ (LANDIS-II-Visualization) Changes to this extension are governed by the Repository Rules from the Technical Advisory Committee.. LANDIS-II Visualization Development




________________________________

**Comment by brmiranda** [comment]
The attached file that I edited seems to work now.  I believe the instructions in the Read me are not quite accurate, because it did not run when I did not include a \<link> tag.  Also, it should be specified that the \<weblinks> section needs to be added to a certain location within the file.  Trial and error led me to add it just after \</output> and that seemed to work.

Note that I had to convert my xml file to txt in order to attach it here.  Rename to .xml and it should work.

[preproc_VizTool_example.txt](https://github.com/LANDIS-II-Foundation/LANDVIZ/files/2069188/preproc_VizTool_example.txt)
